[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_rounds = 200
fs_permissions = [{ access = "read", path = "./broadcast" }]
gas_reports = ["NFTContract"]


[fuzz]
runs = 1000
max_test_rejects=50000

[invariant]
fail_on_revert=true